consul_nomad:
  command: agent -dev -ui -domain=sd -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dev -node=dev1

consul:
  command: agent -dev -ui -domain=sd -bind=127.0.0.1 -datacenter=dev -node=dev1
  
mongo:
  entrypoint: mongod
  command: --nojournal --dbpath ./tmp/mongo --profile=1 --logpath ./log/mongodb.log
  consul:
    - 
      name: mongo
      port: 27017

nsqlookupd:
  entrypoint: nsqlookupd
  consul:
    - 
      port_label: tcp
      port: 4160
    -   
      port_label: http
      port: 4161
      http_check: /ping
      tags:
        - urlprefix-nsqlookupd.localhost/
    
nsqadmin:
  entrypoint: nsqadmin
  command: -lookupd-http-address=127.0.0.1:4161
  consul:
    - 
      port: 4171
      http_check: /ping
      tags:
        - urlprefix-nsq.localhost/

nsqd:
  entrypoint: nsqd
  command: -lookupd-tcp-address=127.0.0.1:4160 -broadcast-address=127.0.0.1 -data-path=./tmp/nsqd -max-msg-size=10485760
  consul:
    - 
      port_label: tcp
      port: 4150
    -   
      port_label: http
      port: 4151
      http_check: /ping
      tags:
        - urlprefix-nsqd.localhost/

fabio:
  entrypoint: fabio
  command: -proxy.addr :80 -insecure -log.level TRACE -log.routes.format all -registry.consul.register.tags urlprefix-fabio.localhost/
  consul:
    -
      # register consul route
      name: consul
      http_check: /v1/health/node/dev1
      port: 8500
      tags:
        - urlprefix-consul.localhost/

nomad:
  command: agent -dev -region=dev -dc=dev -network-interface=en0 -bind=0.0.0.0
