consul:
  command: agent -dev -bootstrap -server -ui -domain=sd -bind=127.0.0.1 -datacenter=dev -data-dir=./tmp/consul/ -node=dev01
  
mongo:
  entrypoint: mongod
  command: --nojournal --dbpath ./tmp/mongo --profile=1 --logpath ./log/mongodb.log
  consul:
    - 
      name: mongo
      port: 27017

nsqlookupd:
  entrypoint: nsqlookupd
  consul:
    - 
      name: nsqlookupd-tcp
      port: 4160
    -   
      name: nsqlookupd-http
      port: 4161
      http_check: /ping
    
nsqadmin:
  entrypoint: nsqadmin
  command: -lookupd-http-address=127.0.0.1:4161
  consul:
    - 
      port: 4171
      http_check: /ping
      tags:
        - urlprefix-nsq.localhost/

nsqd:
  entrypoint: nsqd
  command: -lookupd-tcp-address=127.0.0.1:4160 -broadcast-address=127.0.0.1 -data-path=./tmp/nsqd -max-msg-size=10485760
  consul:
    - 
      name: nsqd-tcp
      port: 4150
    -   
      name: nsqd-http
      port: 4151
      http_check: /ping

fabio:
  entrypoint: fabio
  command: -proxy.addr :80 -log.level TRACE -registry.consul.service.status passing,warning,critical,unknown -insecure
  # consul:
  #   - 
  #     name: fabio
  #     port: 9999
