math:
  path: ~/work/minus5/svckit/example/amp/math
  build: go build --race
  topics:
    - math.v1
    - math.req
  consul:
    -
      http_check: /health_check
      tags:
        - urlprefix-/math strip=/math

chat:
  path: ~/work/minus5/svckit/example/amp/chat
  build: go build --race
  topics:
    - chat
    - chat.req
    - chat.current
  consul:
    -
      http_check: /health_check
      tags:
        - urlprefix-/chat strip=/chat

amp:
  path: ~/work/minus5/svckit/example/amp
  build: go build --race
  consul:
    - 
      name: api
      http_check: /health_check
      tags:
        - urlprefix-/api-debug strip=/api-debug
    - 
      name: api-ws
      port_label: ws
      tags:
        - urlprefix-/api
    - 
      name: api-demo
      port_label: demo
      http_check: /index.html
      tags:
        - urlprefix-/demo strip=/demo
