math:
  path: ~/work/minus5/svckit/example/amp/math
  build: go build --race
  topics:
    - math.v1
    - math.req
  consul:
    -
      http_check: /health_check
      tags:
        - urlprefix-math.localhost

chat:
  path: ~/work/minus5/svckit/example/amp/chat
  build: go build --race
  topics:
    - chat
    - chat.req
    - chat.current
  consul:
    -
      http_check: /health_check
      tags:
        - urlprefix-chat.localhost/

amp:
  path: ~/work/minus5/svckit/example/amp
  build: go build --race
  consul:
    - 
      name: api
      http_check: /health_check
      tags:
        - urlprefix-api.localhost/
    - 
      name: api-ws
      port_label: ws
      tags:
        - urlprefix-/api
    - 
      name: app
      port_label: app
      http_check: /index.html
      tags:
        - urlprefix-/
    - 
      name: api-pooling
      port_label: pooling
      http_check: /health_check
      tags:
        - urlprefix-/pooling strip=/pooling
