math:
  path: ~/work/mnu5/svckit/example/amp/math
  build: go build --race
  topics:
    - math.output
  consul:
    -
      http_check: /health_check
      tags:
        - urlprefix-math.localhost/

amp:
  path: ~/work/mnu5/svckit/example/amp
  build: go build --race
  topics:
    - math.v1
  consul:
    - 
      name: api
      http_check: /health_check
      tags:
        - urlprefix-/api-debug
    - 
      name: api-ws
      port_label: ws
      tags:
        - urlprefix-/api
    - 
      name: api-demo
      port_label: demo
      http_check: /index.html
      tags:
        - urlprefix-/demo strip=/demo
